[harvest]
from = [ "git", "cff" ]

[harvest.cff]
validate = false

[deposit]
mapping = "trainingmaterial_jsonld"

[deposit.trainingmaterial_jsonld]
output = "test_output.json"

[postprocess]
execute = [ "config_record_id" ]
